<?php
return array(
    "total_records" => "السجلات الكلية"
,"search" => "بحث"
,"delete" => "حذف"
,"cancel" => "إلغاء"
,"action" => "عمل"
,"edit" => "تصحيح"
,"del" => "حذف"
,"no_data_in_this_table_click_add_button_below" => "لا توجد بيانات في هذا الجدول. انقر إضافة الزر أدناه."
,"no_fields_in_this_table" => "لا حقول في هذا الجدول!"
,"print" => "طباعة"
,"export" => "تصدير"
,"enable" => "تمكين"
,"disable" => "تعطيل"
,"no_record_found" => "لاتوجدالنتايج•"
,"gender_one" => "S/O"
,"gender_two" => "D/O"
,"branch" => "فرع"
,"equal" => "برابر"
,"more_equal" => "برابر یا زیادہ"
,"less_equal" => "برابر یا کم"
,"not_equal" => "برابر نہیں"
);